name: Deployment pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Run actions/setup-node@v4
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: npm install
        run: npm install

      - name: lint
        run: npm run eslint

      - name: build
        run: npm run build

      - name: Start Application
        run: npm run start-prod &

      - name: test
        run: npm test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: e2e tests
        run: npm run test:e2e

        if: ${{ github.event_name == 'push' }}

      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Health Check
        run: |
          echo "Waiting for server to start..."
          sleep 30
          echo "Checking health of deployed app..."
          response=$(curl --fail https://full-stack-open-pokedex-jvcn.onrender.com/healthz)
          if [ "$response" == "ok" ]; then
            echo "Health check passed!"
          else
            echo "Health check failed!"
            exit 1
          fi
